use_frameworks!

platform :ios, '8.0'

target 'ECPrivacyCheckTools_Example' do
  pod 'ECPrivacyCheckTools', :path => '../'

  target 'ECPrivacyCheckTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
